language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
branches:
    only:
        - master
install: pip install -r test-requirements.txt
script: ./test.sh
after_success: coveralls
